"""Schema creation helper.

Alembic is the migration tool of record (§13), but v1 has no migration
history yet — this creates the schema from the ORM metadata for dev and
tests. The first Alembic revision should be autogenerated from this same
metadata when the schema stabilizes.
"""

from app.db import Base, engine
from app import models  # noqa: F401  — registers all mappers on Base.metadata


def create_all(target_engine=None) -> None:
    Base.metadata.create_all(target_engine or engine)


def drop_all(target_engine=None) -> None:
    Base.metadata.drop_all(target_engine or engine)


if __name__ == "__main__":
    create_all()
    print("Schema created.")
